## NUMPY

Numpy stands for 'Numerical Python'.It is a Linear Algebra library. It is used to work with multidimensional
array objects. Most data sciense librararies in python builds on top of numpy.
Numpy objects are homogeneous multidimensional arrays (same type).

In [1]:
import numpy as np

In [2]:
# one dimensional array

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
# two dimensional
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [5]:
#to find the shape of an np array

In [6]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a.shape

(2, 3)

In [8]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
#to check the dimension
a = np.array([1,2,3])
a.ndim

1

In [10]:
a = np.array([[1,2,3],[4,5,6]])
a.ndim

2

In [11]:
a = np.arange(10) 
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
a.size

10

In [14]:
b = np.array([[1,2,3],[4,5,6]])
b.size

6

In [17]:
#The type of the array can also be explicitly specified at creation time
%config IPCompleter.greedy=True

In [18]:
a = np.array([1,2,3],dtype = np.complex)
a

array([ 1.+0.j,  2.+0.j,  3.+0.j])

In [19]:
a = np.array([1,2,3],dtype = np.int32)
a

array([1, 2, 3])

In [20]:
a = np.array([1,2,3],dtype = np.float)
a

array([ 1.,  2.,  3.])

In [32]:
#array of zeros
#by default the dtype will be float

In [33]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [34]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [35]:
#array of ones

In [36]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [37]:
#Some basic operations

In [38]:
a = np.array( [10,20,30,40] )
b = np.array([2,4,6,8])

In [39]:
a+b

array([12, 24, 36, 48])

In [40]:
a-b

array([ 8, 16, 24, 32])

In [43]:
#* is element wise multiplication
a*b

array([ 20,  80, 180, 320])

In [44]:
b**2

array([ 4, 16, 36, 64])

In [45]:
#matrix product (dot product) 

In [47]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,1],[1,1]])

In [53]:
#matrix (or dot product)
A@B

array([[3, 3],
       [7, 7]])

In [49]:
A = np.array([[1,2],[3,4]])

In [50]:
#sum of all elements
A.sum()

10

In [54]:
#maximum value element
A.max()

4

In [55]:
#minimum value element
A.min()

1

In [60]:
#Slicing

In [62]:
a =np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a[0:3]

array([1, 2, 3])

In [70]:
a =np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [72]:
a[0:1]

array([[1, 2, 3]])

In [73]:
a[0:2]

array([[1, 2, 3],
       [3, 4, 5]])

In [74]:
#iterating

In [75]:
a =np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [77]:
for row in a:
    print(row)

[1 2 3]
[3 4 5]


In [79]:
for row in a:
    for i in row:
        print(i)

1
2
3
3
4
5


In [80]:
# element wise iteration:

In [81]:
for element in a.flat:
    print(element)

1
2
3
3
4
5


In [82]:
#stacking arrays

In [83]:
a =np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [84]:
b =np.array([[9,8,7],[6,4,5]])
b

array([[9, 8, 7],
       [6, 4, 5]])

In [89]:
np.vstack((a,b))

array([[1, 2, 3],
       [3, 4, 5],
       [9, 8, 7],
       [6, 4, 5]])